version: "3.8"
services:
  secretsips:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    networks:
      - shared-net
    restart: unless-stopped

networks:
  shared-net:
    external: true
