version: "3.8"
services:
  secret-sips-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5002
    ports:
      - "5002:5002"
    container_name: secret-sips-server
    networks:
      - shared-net
    restart: unless-stopped
    expose:
      - "5002"

networks:
  shared-net:
    external: true
