version: "3.8"
services:
  secretsips:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5002
    ports:
      - "5002:5002"
    networks:
      - shared-net
    restart: unless-stopped

networks:
  shared-net:
    external: true
